import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import TitleBar from "@/components/Home/TitleBar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <link href="https://fonts.googleapis.com/css2?family=Calistoga&display=swap" rel="stylesheet"/>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <link href="https://fonts.googleapis.com/css2?family=Martian+Mono:wght@100..800&display=swap"
                  rel="stylesheet"/>
            <title>Checkrr</title>
        </head>
        <body className={inter.className}>
        <div className={""}>
            <div className={"md:ml-20 ml-0"} >
                <TitleBar/>{children}
            </div>
        </div>
        </body>
        </html>
    );
}
